# Generated by Django 5.2.5 on 2025-08-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='open_hours',
            field=models.TimeField(null=True),
        ),
    ]
