# Generated by Django 5.2.5 on 2025-08-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_generalinfo_open_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='open_hours',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
